name: othello_game
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.9.1
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.1.2

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  assets:
    - assets/Astronaut.glb
  
