name: othello_game
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  firebase_core: ^3.8.1
  http: ^1.0.0
  firebase_messaging: ^15.0.1
  firebase_messaging_web: ^3.9.5
  flutter_local_notifications: ^17.1.2
  flutter:
    sdk: flutter

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  assets:
    - assets/Astronaut.glb
  
