name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.0

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  
