name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  flame: ^1.21.0

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  
