name: othello_game
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0
  firebase_core: ^1.10.6
  firebase_database: ^9.0.8
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  provider: ^6.1.2

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  
