// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ddEwE9Cy9rvh7Rdf5ddVBAY8aEKj9cM',
    appId: '1:416064751674:web:a2808bdfffe75a012ccd03',
    messagingSenderId: '416064751674',
    projectId: 'seat-change-optimization',
    authDomain: 'seat-change-optimization.firebaseapp.com',
    storageBucket: 'seat-change-optimization.appspot.com',
    measurementId: 'G-Q6TSN9L1TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGq78MrrPMzcFarzt4wow7__4HMv6BGpw',
    appId: '1:416064751674:android:65e7060f4bf439582ccd03',
    messagingSenderId: '416064751674',
    projectId: 'seat-change-optimization',
    storageBucket: 'seat-change-optimization.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD97Kzbdpf7LeG4TGxcthdTsP0GkktOz0w',
    appId: '1:416064751674:ios:e711b474581b570a2ccd03',
    messagingSenderId: '416064751674',
    projectId: 'seat-change-optimization',
    storageBucket: 'seat-change-optimization.appspot.com',
    iosBundleId: 'com.example.seatChangeOptimization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD97Kzbdpf7LeG4TGxcthdTsP0GkktOz0w',
    appId: '1:416064751674:ios:e711b474581b570a2ccd03',
    messagingSenderId: '416064751674',
    projectId: 'seat-change-optimization',
    storageBucket: 'seat-change-optimization.appspot.com',
    iosBundleId: 'com.example.seatChangeOptimization',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ddEwE9Cy9rvh7Rdf5ddVBAY8aEKj9cM',
    appId: '1:416064751674:web:27e8673e8034bed82ccd03',
    messagingSenderId: '416064751674',
    projectId: 'seat-change-optimization',
    authDomain: 'seat-change-optimization.firebaseapp.com',
    storageBucket: 'seat-change-optimization.appspot.com',
    measurementId: 'G-NCKKW7774G',
  );
}
